package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.cds.runtime.CDSInstanceTable;
import org.modelingvalue.collections.Collection;
import org.modelingvalue.cds.runtime.CDSObject;

public class AntistollingsPaden_ObjectTable implements CDSInstanceTable {
  @Override
  public Collection<? extends CDSObject> getInstances() {
    return Collection.of(of("VKA"), of("DOAC"), of("TAR"), of("TAR-P2Y12-remmers"), of("DAPT"), of("TripleTherapie"));
  }
  private CDSObject of(String id) {
    AntistollingsPad_Concept o = new AntistollingsPad_Concept(id);
    return o;
  }
}
