package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.dclare.Observed;
import org.modelingvalue.dclare.Observer;
import java.util.function.Function;
import java.util.function.Predicate;
import org.modelingvalue.collections.Set;
import org.modelingvalue.dclare.MutableClass;
import org.modelingvalue.cds.runtime.CDSClass;
import org.modelingvalue.cds.runtime.CDSUniverse;

public class EnkelvoudigeMedicijnGroep_Concept extends MedicijnGroep_Concept {


  public static final Observed<EnkelvoudigeMedicijnGroep_Concept, Boolean> ENKELVOUDIGEMEDICIJNGROEPSAMENSTELLING_R0_ROW = Observed.<EnkelvoudigeMedicijnGroep_Concept,Boolean>of("EnkelvoudigeMedicijnGroepSamenstelling_r0", null);

  public static final Observer<EnkelvoudigeMedicijnGroep_Concept> ENKELVOUDIGEMEDICIJNGROEPSAMENSTELLING_R0_OBSERVER = Observer.of("EnkelvoudigeMedicijnGroepSamenstelling_r0", EnkelvoudigeMedicijnGroep_Concept.ENKELVOUDIGEMEDICIJNGROEPSAMENSTELLING_R0_ROW, new Function<EnkelvoudigeMedicijnGroep_Concept, Boolean>() {
    public Boolean apply(EnkelvoudigeMedicijnGroep_Concept it) {
      return true;
    }
  });
  public static final Observer<EnkelvoudigeMedicijnGroep_Concept> ENKELVOUDIGEMEDICIJNGROEPSAMENSTELLING_C0_R0_OBSERVER = Observer.of("EnkelvoudigeMedicijnGroepSamenstelling_c0_r0", MedicijnGroep_Concept.SAMENSTELLING_OBSERVED, new Predicate<EnkelvoudigeMedicijnGroep_Concept>() {
    @Override
    public boolean test(EnkelvoudigeMedicijnGroep_Concept a) {
      return EnkelvoudigeMedicijnGroep_Concept.ENKELVOUDIGEMEDICIJNGROEPSAMENSTELLING_R0_ROW.get(a) == Boolean.TRUE;
    }
  }, new Function<EnkelvoudigeMedicijnGroep_Concept, Set>() {
    public Set apply(EnkelvoudigeMedicijnGroep_Concept it) {
      return it.EnkelvoudigeMedicijnGroepSamenstelling_c0_r0();
    }
  });

  private static final MutableClass D_CLASS = CDSClass.of(EnkelvoudigeMedicijnGroep_Concept.class);

  public EnkelvoudigeMedicijnGroep_Concept(Object id) {
    super(id);
  }

  @Override
  public MutableClass dClass() {
    return D_CLASS;
  }

  public Set EnkelvoudigeMedicijnGroepSamenstelling_c0() {
    return MedicijnGroep_Concept.SAMENSTELLING_OBSERVED.get(this);
  }
  public Set EnkelvoudigeMedicijnGroepSamenstelling_c0_r0() {
    return Set.of(new Object[]{this});
  }

  public static class ConceptUniverse extends EnkelvoudigeMedicijnGroep_Concept implements CDSUniverse {
    private static final MutableClass D_CLASS = CDSClass.of(ConceptUniverse.class);

    public ConceptUniverse(Object id) {
      super(id);
    }

    @Override
    public MutableClass dClass() {
      return ConceptUniverse.D_CLASS;
    }
  }
}
