package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.cds.runtime.CDSInstanceTable;
import org.modelingvalue.collections.Collection;
import org.modelingvalue.cds.runtime.CDSObject;
import org.modelingvalue.collections.Set;

public class EnkelvoudigeMedicijnGroepen_ObjectTable implements CDSInstanceTable {
  @Override
  public Collection<? extends CDSObject> getInstances() {
    return Collection.of(of("TAR", Set.of(new Object[]{new GeneriekMedicijn_Concept("acetylsalicylzuur"), new GeneriekMedicijn_Concept("carbasalaatcalcium"), new GeneriekMedicijn_Concept("dipyridamol")}), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("TAR")})), of("VKA", Set.of(new Object[]{new GeneriekMedicijn_Concept("acenocoumarol"), new GeneriekMedicijn_Concept("fenprocoumon")}), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("VKA")})), of("DOAC", Set.of(new Object[]{new GeneriekMedicijn_Concept("dabigatran"), new GeneriekMedicijn_Concept("rivaroxaban"), new GeneriekMedicijn_Concept("apixaban"), new GeneriekMedicijn_Concept("edoxaban")}), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("DOAC")})), of("TAR-P2Y12-remmers", Set.of(new Object[]{new GeneriekMedicijn_Concept("clopidogrel"), new GeneriekMedicijn_Concept("prasugrel"), new GeneriekMedicijn_Concept("ticagrelor")}), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("TAR-P2Y12-remmers")})));
  }
  private CDSObject of(String id, Set medicijnen, Set samenstelling) {
    EnkelvoudigeMedicijnGroep_Concept o = new EnkelvoudigeMedicijnGroep_Concept(id);
    EnkelvoudigeMedicijnGroep_Concept.MEDICIJNEN_OBSERVED.set(o, medicijnen);
    EnkelvoudigeMedicijnGroep_Concept.SAMENSTELLING_OBSERVED.set(o, samenstelling);
    return o;
  }
}
