package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.cds.runtime.CDSInstanceTable;
import org.modelingvalue.collections.Collection;
import org.modelingvalue.cds.runtime.CDSObject;

public class GeneriekeMedicijnen_ObjectTable implements CDSInstanceTable {
  @Override
  public Collection<? extends CDSObject> getInstances() {
    return Collection.of(of("acenocoumarol", new GeneriekMedicijn_Concept("acenocoumarol"), new EnkelvoudigeMedicijnGroep_Concept("VKA")), of("fenprocoumon", new GeneriekMedicijn_Concept("fenprocoumon"), new EnkelvoudigeMedicijnGroep_Concept("VKA")), of("dabigatran", new GeneriekMedicijn_Concept("dabigatran"), new EnkelvoudigeMedicijnGroep_Concept("DOAC")), of("rivaroxaban", new GeneriekMedicijn_Concept("rivaroxaban"), new EnkelvoudigeMedicijnGroep_Concept("DOAC")), of("apixaban", new GeneriekMedicijn_Concept("apixaban"), new EnkelvoudigeMedicijnGroep_Concept("DOAC")), of("edoxaban", new GeneriekMedicijn_Concept("edoxaban"), new EnkelvoudigeMedicijnGroep_Concept("DOAC")), of("acetylsalicylzuur", new GeneriekMedicijn_Concept("acetylsalicylzuur"), new EnkelvoudigeMedicijnGroep_Concept("TAR")), of("carbasalaatcalcium", new GeneriekMedicijn_Concept("carbasalaatcalcium"), new EnkelvoudigeMedicijnGroep_Concept("TAR")), of("dipyridamol", new GeneriekMedicijn_Concept("dipyridamol"), new EnkelvoudigeMedicijnGroep_Concept("TAR")), of("clopidogrel", new GeneriekMedicijn_Concept("clopidogrel"), new EnkelvoudigeMedicijnGroep_Concept("TAR-P2Y12-remmers")), of("prasugrel", new GeneriekMedicijn_Concept("prasugrel"), new EnkelvoudigeMedicijnGroep_Concept("TAR-P2Y12-remmers")), of("ticagrelor", new GeneriekMedicijn_Concept("ticagrelor"), new EnkelvoudigeMedicijnGroep_Concept("TAR-P2Y12-remmers")), of("asasantin", new GeneriekMedicijn_Concept("asasantin"), new MeervoudigeMedicijnGroep_Concept("DAPT")), of("duoplavin", new GeneriekMedicijn_Concept("duoplavin"), new MeervoudigeMedicijnGroep_Concept("DAPT")));
  }
  private CDSObject of(String id, GeneriekMedicijn_Concept generiek, MedicijnGroep_Concept groep) {
    GeneriekMedicijn_Concept o = new GeneriekMedicijn_Concept(id);
    GeneriekMedicijn_Concept.GENERIEK_OBSERVED.set(o, generiek);
    GeneriekMedicijn_Concept.GROEP_OBSERVED.set(o, groep);
    return o;
  }
}
