package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.dclare.Observed;
import java.util.function.Supplier;
import org.modelingvalue.dclare.Setable;
import org.modelingvalue.collections.Set;
import org.modelingvalue.dclare.MutableClass;
import org.modelingvalue.cds.runtime.CDSClass;
import org.modelingvalue.cds.runtime.CDSUniverse;

public class GeneriekMedicijn_Concept extends Medicijn_Concept {

  public static final Observed<GeneriekMedicijn_Concept, MedicijnGroep_Concept> GROEP_OBSERVED = Observed.<GeneriekMedicijn_Concept,MedicijnGroep_Concept>of("=groep", null, new Supplier<Setable<?, ?>>() {
    @Override
    public Setable<?, ?> get() {
      return MedicijnGroep_Concept.MEDICIJNEN_OBSERVED;
    }
  });
  public static final Observed<GeneriekMedicijn_Concept, Set> SPECIFIEKE_OBSERVED = Observed.<GeneriekMedicijn_Concept,Set>of("=specifieke", Set.of(), new Supplier<Setable<?, ?>>() {
    @Override
    public Setable<?, ?> get() {
      return Medicijn_Concept.GENERIEK_OBSERVED;
    }
  });



  private static final MutableClass D_CLASS = CDSClass.of(GeneriekMedicijn_Concept.class);

  public GeneriekMedicijn_Concept(Object id) {
    super(id);
  }

  @Override
  public MutableClass dClass() {
    return D_CLASS;
  }


  public static class ConceptUniverse extends GeneriekMedicijn_Concept implements CDSUniverse {
    private static final MutableClass D_CLASS = CDSClass.of(ConceptUniverse.class);

    public ConceptUniverse(Object id) {
      super(id);
    }

    @Override
    public MutableClass dClass() {
      return ConceptUniverse.D_CLASS;
    }
  }
}
