package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.cds.runtime.CDSObject;
import org.modelingvalue.dclare.Observed;
import java.util.function.Supplier;
import org.modelingvalue.dclare.Setable;
import java.math.BigInteger;
import org.modelingvalue.dclare.MutableClass;
import org.modelingvalue.cds.runtime.CDSClass;
import org.modelingvalue.cds.runtime.CDSUniverse;

public class MedicijnGebruik_Concept extends CDSObject {

  public static final Observed<MedicijnGebruik_Concept, Patient_Concept> PATIENT_OBSERVED = Observed.<MedicijnGebruik_Concept,Patient_Concept>of("=patient", null, new Supplier<Setable<?, ?>>() {
    @Override
    public Setable<?, ?> get() {
      return Patient_Concept.MEDICIJNENGEBRUIK_OBSERVED;
    }
  });
  public static final Observed<MedicijnGebruik_Concept, Medicijn_Concept> MEDICIJN_OBSERVED = Observed.<MedicijnGebruik_Concept,Medicijn_Concept>of("=medicijn", null, null);
  public static final Observed<MedicijnGebruik_Concept, BigInteger> INAMEPERDAG_OBSERVED = Observed.<MedicijnGebruik_Concept,BigInteger>of("=inamePerDag", null, null);



  private static final MutableClass D_CLASS = CDSClass.of(MedicijnGebruik_Concept.class);

  public MedicijnGebruik_Concept(Object id) {
    super(id);
  }

  @Override
  public MutableClass dClass() {
    return D_CLASS;
  }


  public static class ConceptUniverse extends MedicijnGebruik_Concept implements CDSUniverse {
    private static final MutableClass D_CLASS = CDSClass.of(ConceptUniverse.class);

    public ConceptUniverse(Object id) {
      super(id);
    }

    @Override
    public MutableClass dClass() {
      return ConceptUniverse.D_CLASS;
    }
  }
}
