package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.cds.runtime.CDSObject;
import org.modelingvalue.dclare.Observed;
import java.util.function.Supplier;
import org.modelingvalue.dclare.Setable;
import org.modelingvalue.dclare.MutableClass;
import org.modelingvalue.cds.runtime.CDSClass;
import org.modelingvalue.cds.runtime.CDSUniverse;

public class Medicijn_Concept extends CDSObject {

  public static final Observed<Medicijn_Concept, GeneriekMedicijn_Concept> GENERIEK_OBSERVED = Observed.<Medicijn_Concept,GeneriekMedicijn_Concept>of("=generiek", null, new Supplier<Setable<?, ?>>() {
    @Override
    public Setable<?, ?> get() {
      return GeneriekMedicijn_Concept.SPECIFIEKE_OBSERVED;
    }
  });



  private static final MutableClass D_CLASS = CDSClass.of(Medicijn_Concept.class);

  public Medicijn_Concept(Object id) {
    super(id);
  }

  @Override
  public MutableClass dClass() {
    return D_CLASS;
  }


  public static class ConceptUniverse extends Medicijn_Concept implements CDSUniverse {
    private static final MutableClass D_CLASS = CDSClass.of(ConceptUniverse.class);

    public ConceptUniverse(Object id) {
      super(id);
    }

    @Override
    public MutableClass dClass() {
      return ConceptUniverse.D_CLASS;
    }
  }
}
