package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.cds.runtime.CDSInstanceTable;
import org.modelingvalue.collections.Collection;
import org.modelingvalue.cds.runtime.CDSObject;
import org.modelingvalue.collections.Set;

public class MedicijnGroepen_ObjectTable implements CDSInstanceTable {
  @Override
  public Collection<? extends CDSObject> getInstances() {
    return Collection.of(of("TAR", Set.of(new Object[]{new Medicijn_Concept("acetylsalicylzuur"), new Medicijn_Concept("carbasalaatcalcium"), new Medicijn_Concept("dipyridamol"), new Medicijn_Concept("aspirine"), new Medicijn_Concept("persantin"), new Medicijn_Concept("ascal")}), Set.of(new Object[]{})), of("VKA", Set.of(new Object[]{new Medicijn_Concept("acenocoumarol"), new Medicijn_Concept("fenprocoumon"), new Medicijn_Concept("sintrom mitis"), new Medicijn_Concept("marcoumar")}), Set.of(new Object[]{})), of("DOAC", Set.of(new Object[]{new Medicijn_Concept("dabigatran"), new Medicijn_Concept("rivaroxaban"), new Medicijn_Concept("apixaban"), new Medicijn_Concept("edoxaban"), new Medicijn_Concept("lixiana"), new Medicijn_Concept("eliquis"), new Medicijn_Concept("xarelto"), new Medicijn_Concept("pradaxa")}), Set.of(new Object[]{})), of("TAR-P2Y12-remmers", Set.of(new Object[]{new Medicijn_Concept("clopidogrel"), new Medicijn_Concept("prasugrel"), new Medicijn_Concept("ticagrelor"), new Medicijn_Concept("brilique"), new Medicijn_Concept("plavix"), new Medicijn_Concept("grepid"), new Medicijn_Concept("efient"), new Medicijn_Concept("iscover")}), Set.of(new Object[]{})), of("DAPT", Set.of(new Object[]{new Medicijn_Concept("asasantin"), new Medicijn_Concept("duoplavin")}), Set.of(new Object[]{new MedicijnGroep_Concept("TAR"), new MedicijnGroep_Concept("TAR-P2Y12-remmers")})));
  }
  private CDSObject of(String id, Set medicijnen, Set samenstelling) {
    MedicijnGroep_Concept o = new MedicijnGroep_Concept(id);
    MedicijnGroep_Concept.MEDICIJNEN_OBSERVED.set(o, medicijnen);
    MedicijnGroep_Concept.SAMENSTELLING_OBSERVED.set(o, samenstelling);
    return o;
  }
}
