package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.cds.runtime.CDSInstanceTable;
import org.modelingvalue.collections.Collection;
import org.modelingvalue.cds.runtime.CDSObject;
import java.math.BigInteger;

public class MedicijnGebruiken_ObjectTable implements CDSInstanceTable {
  @Override
  public Collection<? extends CDSObject> getInstances() {
    return Collection.of(of("Piet carbasalaatcalcium", new Patient_Concept("Piet"), new Medicijn_Concept("carbasalaatcalcium"), BigInteger.valueOf(1L)));
  }
  private CDSObject of(String id, Patient_Concept patient, Medicijn_Concept medicijn, BigInteger aantalPerDag) {
    MedicijnGebruik_Concept o = new MedicijnGebruik_Concept(id);
    MedicijnGebruik_Concept.PATIENT_OBSERVED.set(o, patient);
    MedicijnGebruik_Concept.MEDICIJN_OBSERVED.set(o, medicijn);
    MedicijnGebruik_Concept.AANTALPERDAG_OBSERVED.set(o, aantalPerDag);
    return o;
  }
}
