package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.cds.runtime.CDSInstanceTable;
import org.modelingvalue.collections.Collection;
import org.modelingvalue.cds.runtime.CDSObject;
import org.modelingvalue.collections.Set;

public class MeervoudigeMedicijnGroepen_ObjectTable implements CDSInstanceTable {
  @Override
  public Collection<? extends CDSObject> getInstances() {
    return Collection.of(of("DAPT", Set.of(new Object[]{new GeneriekMedicijn_Concept("asasantin"), new GeneriekMedicijn_Concept("duoplavin")}), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("TAR"), new EnkelvoudigeMedicijnGroep_Concept("TAR-P2Y12-remmers")})));
  }
  private CDSObject of(String id, Set medicijnen, Set samenstelling) {
    MeervoudigeMedicijnGroep_Concept o = new MeervoudigeMedicijnGroep_Concept(id);
    MeervoudigeMedicijnGroep_Concept.MEDICIJNEN_OBSERVED.set(o, medicijnen);
    MeervoudigeMedicijnGroep_Concept.SAMENSTELLING_OBSERVED.set(o, samenstelling);
    return o;
  }
}
