package serviceLogic;

/*Generated by MPS */

import org.springframework.web.bind.annotation.RestController;
import org.modelingvalue.cds.runtime.CDSRestController;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestBody;
import javax.servlet.http.HttpSession;
import org.modelingvalue.cds.runtime.CDSStoreAndFactory;

@RestController
public class PatientAntistollingsPad_RestController extends CDSRestController {
  @RequestMapping(value = "/PatientMedicijnGebruikPad_TransactieType")
  public String PatientMedicijnGebruikPad_TransactieType_EntryPoint(@RequestBody String json, HttpSession session) {
    return genericEntryPoint(json, session);
  }

  public CDSStoreAndFactory createStoreAndFactory(String id) {
    return new PatientAntistollingsPad_StoreAndFactory(id);
  }
}
