package serviceLogic;

/*Generated by MPS */

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.boot.SpringApplication;

@SpringBootApplication
@ComponentScan
public class PatientAntistollingsPad_Application {
  public static void main(String[] args) {
    SpringApplication.run(PatientAntistollingsPad_Application.class, args);
  }
}
