package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.cds.runtime.CDSObject;
import org.modelingvalue.dclare.Observed;
import org.modelingvalue.collections.Set;
import java.util.function.Supplier;
import org.modelingvalue.dclare.Setable;
import org.modelingvalue.dclare.Observer;
import java.util.function.Function;
import java.util.function.Predicate;
import org.modelingvalue.dclare.MutableClass;
import org.modelingvalue.cds.runtime.CDSClass;
import runtime.CDMRuntimeUtil;
import org.modelingvalue.collections.Collection;
import cdm.lang.java.BaseDispatcher__cdm_lang;
import org.modelingvalue.cds.runtime.CDSUniverse;

public class Patient_Concept extends CDSObject {

  public static final Observed<Patient_Concept, Set> MEDICIJNENGEBRUIK_OBSERVED = Observed.<Patient_Concept,Set>of("=medicijnenGebruik", Set.of(), new Supplier<Setable<?, ?>>() {
    @Override
    public Setable<?, ?> get() {
      return MedicijnGebruik_Concept.PATIENT_OBSERVED;
    }
  });
  public static final Observed<Patient_Concept, AntistollingsPad_Concept> ANTISTOLLINGSPAD_OBSERVED = Observed.<Patient_Concept,AntistollingsPad_Concept>of("=antistollingsPad", null, null);

  public static final Observed<Patient_Concept, Set> PATIENTMEDICIJNGEBRUIKPAD_C0_COLUMN = Observed.<Patient_Concept,Set>of("PatientMedicijnGebruikPad_c0", null);
  public static final Observed<Patient_Concept, Boolean> PATIENTMEDICIJNGEBRUIKPAD_R0_ROW = Observed.<Patient_Concept,Boolean>of("PatientMedicijnGebruikPad_r0", null);
  public static final Observed<Patient_Concept, Boolean> PATIENTMEDICIJNGEBRUIKPAD_R1_ROW = Observed.<Patient_Concept,Boolean>of("PatientMedicijnGebruikPad_r1", null);
  public static final Observed<Patient_Concept, Boolean> PATIENTMEDICIJNGEBRUIKPAD_R2_ROW = Observed.<Patient_Concept,Boolean>of("PatientMedicijnGebruikPad_r2", null);
  public static final Observed<Patient_Concept, Boolean> PATIENTMEDICIJNGEBRUIKPAD_R3_ROW = Observed.<Patient_Concept,Boolean>of("PatientMedicijnGebruikPad_r3", null);
  public static final Observed<Patient_Concept, Boolean> PATIENTMEDICIJNGEBRUIKPAD_R4_ROW = Observed.<Patient_Concept,Boolean>of("PatientMedicijnGebruikPad_r4", null);
  public static final Observed<Patient_Concept, Boolean> PATIENTMEDICIJNGEBRUIKPAD_R5_ROW = Observed.<Patient_Concept,Boolean>of("PatientMedicijnGebruikPad_r5", null);
  public static final Observed<Patient_Concept, Boolean> PATIENTMEDICIJNGEBRUIKPAD_R6_ROW = Observed.<Patient_Concept,Boolean>of("PatientMedicijnGebruikPad_r6", null);

  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_C0_OBSERVER = Observer.of("PatientMedicijnGebruikPad_c0", Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_C0_COLUMN, new Function<Patient_Concept, Set>() {
    public Set apply(Patient_Concept it) {
      return it.PatientMedicijnGebruikPad_c0();
    }
  });
  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_R0_OBSERVER = Observer.of("PatientMedicijnGebruikPad_r0", Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_R0_ROW, new Function<Patient_Concept, Boolean>() {
    public Boolean apply(Patient_Concept it) {
      return true && it.PatientMedicijnGebruikPad_c0_r0() == Boolean.TRUE;
    }
  });
  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_R1_OBSERVER = Observer.of("PatientMedicijnGebruikPad_r1", Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_R1_ROW, new Function<Patient_Concept, Boolean>() {
    public Boolean apply(Patient_Concept it) {
      return true && it.PatientMedicijnGebruikPad_c0_r1() == Boolean.TRUE;
    }
  });
  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_R2_OBSERVER = Observer.of("PatientMedicijnGebruikPad_r2", Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_R2_ROW, new Function<Patient_Concept, Boolean>() {
    public Boolean apply(Patient_Concept it) {
      return true && it.PatientMedicijnGebruikPad_c0_r2() == Boolean.TRUE;
    }
  });
  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_R3_OBSERVER = Observer.of("PatientMedicijnGebruikPad_r3", Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_R3_ROW, new Function<Patient_Concept, Boolean>() {
    public Boolean apply(Patient_Concept it) {
      return true && it.PatientMedicijnGebruikPad_c0_r3() == Boolean.TRUE;
    }
  });
  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_R4_OBSERVER = Observer.of("PatientMedicijnGebruikPad_r4", Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_R4_ROW, new Function<Patient_Concept, Boolean>() {
    public Boolean apply(Patient_Concept it) {
      return true && it.PatientMedicijnGebruikPad_c0_r4() == Boolean.TRUE;
    }
  });
  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_R5_OBSERVER = Observer.of("PatientMedicijnGebruikPad_r5", Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_R5_ROW, new Function<Patient_Concept, Boolean>() {
    public Boolean apply(Patient_Concept it) {
      return true && it.PatientMedicijnGebruikPad_c0_r5() == Boolean.TRUE;
    }
  });
  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_R6_OBSERVER = Observer.of("PatientMedicijnGebruikPad_r6", Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_R6_ROW, new Function<Patient_Concept, Boolean>() {
    public Boolean apply(Patient_Concept it) {
      return true && it.PatientMedicijnGebruikPad_c0_r6() == Boolean.TRUE;
    }
  });
  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_C1_R0_OBSERVER = Observer.of("PatientMedicijnGebruikPad_c1_r0", Patient_Concept.ANTISTOLLINGSPAD_OBSERVED, new Predicate<Patient_Concept>() {
    @Override
    public boolean test(Patient_Concept a) {
      return Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_R0_ROW.get(a) == Boolean.TRUE;
    }
  }, new Function<Patient_Concept, AntistollingsPad_Concept>() {
    public AntistollingsPad_Concept apply(Patient_Concept it) {
      return it.PatientMedicijnGebruikPad_c1_r0();
    }
  });
  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_C1_R1_OBSERVER = Observer.of("PatientMedicijnGebruikPad_c1_r1", Patient_Concept.ANTISTOLLINGSPAD_OBSERVED, new Predicate<Patient_Concept>() {
    @Override
    public boolean test(Patient_Concept a) {
      return Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_R1_ROW.get(a) == Boolean.TRUE;
    }
  }, new Function<Patient_Concept, AntistollingsPad_Concept>() {
    public AntistollingsPad_Concept apply(Patient_Concept it) {
      return it.PatientMedicijnGebruikPad_c1_r1();
    }
  });
  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_C1_R2_OBSERVER = Observer.of("PatientMedicijnGebruikPad_c1_r2", Patient_Concept.ANTISTOLLINGSPAD_OBSERVED, new Predicate<Patient_Concept>() {
    @Override
    public boolean test(Patient_Concept a) {
      return Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_R2_ROW.get(a) == Boolean.TRUE;
    }
  }, new Function<Patient_Concept, AntistollingsPad_Concept>() {
    public AntistollingsPad_Concept apply(Patient_Concept it) {
      return it.PatientMedicijnGebruikPad_c1_r2();
    }
  });
  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_C1_R3_OBSERVER = Observer.of("PatientMedicijnGebruikPad_c1_r3", Patient_Concept.ANTISTOLLINGSPAD_OBSERVED, new Predicate<Patient_Concept>() {
    @Override
    public boolean test(Patient_Concept a) {
      return Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_R3_ROW.get(a) == Boolean.TRUE;
    }
  }, new Function<Patient_Concept, AntistollingsPad_Concept>() {
    public AntistollingsPad_Concept apply(Patient_Concept it) {
      return it.PatientMedicijnGebruikPad_c1_r3();
    }
  });
  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_C1_R4_OBSERVER = Observer.of("PatientMedicijnGebruikPad_c1_r4", Patient_Concept.ANTISTOLLINGSPAD_OBSERVED, new Predicate<Patient_Concept>() {
    @Override
    public boolean test(Patient_Concept a) {
      return Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_R4_ROW.get(a) == Boolean.TRUE;
    }
  }, new Function<Patient_Concept, AntistollingsPad_Concept>() {
    public AntistollingsPad_Concept apply(Patient_Concept it) {
      return it.PatientMedicijnGebruikPad_c1_r4();
    }
  });
  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_C1_R5_OBSERVER = Observer.of("PatientMedicijnGebruikPad_c1_r5", Patient_Concept.ANTISTOLLINGSPAD_OBSERVED, new Predicate<Patient_Concept>() {
    @Override
    public boolean test(Patient_Concept a) {
      return Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_R5_ROW.get(a) == Boolean.TRUE;
    }
  }, new Function<Patient_Concept, AntistollingsPad_Concept>() {
    public AntistollingsPad_Concept apply(Patient_Concept it) {
      return it.PatientMedicijnGebruikPad_c1_r5();
    }
  });
  public static final Observer<Patient_Concept> PATIENTMEDICIJNGEBRUIKPAD_C1_R6_OBSERVER = Observer.of("PatientMedicijnGebruikPad_c1_r6", Patient_Concept.ANTISTOLLINGSPAD_OBSERVED, new Predicate<Patient_Concept>() {
    @Override
    public boolean test(Patient_Concept a) {
      return Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_R6_ROW.get(a) == Boolean.TRUE;
    }
  }, new Function<Patient_Concept, AntistollingsPad_Concept>() {
    public AntistollingsPad_Concept apply(Patient_Concept it) {
      return it.PatientMedicijnGebruikPad_c1_r6();
    }
  });

  private static final MutableClass D_CLASS = CDSClass.of(Patient_Concept.class);

  public Patient_Concept(Object id) {
    super(id);
  }

  @Override
  public MutableClass dClass() {
    return D_CLASS;
  }

  public Set PatientMedicijnGebruikPad_c0() {
    return as_xl4sqf_a0a0a53(as_xl4sqf_a0a0a0a0a53(Patient_Concept.MEDICIJNENGEBRUIK_OBSERVED.get(this).flatMap(new Function<MedicijnGebruik_Concept, Set<Object>>() {
      @Override
      public Set<Object> apply(MedicijnGebruik_Concept e) {
        return CDMRuntimeUtil.toSet(MedicijnGebruik_Concept.MEDICIJN_OBSERVED.get(e));
      }
    }), Collection.class).toSet().flatMap(new Function<Medicijn_Concept, Set<Object>>() {
      @Override
      public Set<Object> apply(Medicijn_Concept e) {
        return CDMRuntimeUtil.toSet(Medicijn_Concept.SAMENSTELLING_OBSERVED.get(e));
      }
    }), Collection.class).toSet();
  }
  public AntistollingsPad_Concept PatientMedicijnGebruikPad_c1() {
    return Patient_Concept.ANTISTOLLINGSPAD_OBSERVED.get(this);
  }
  public Boolean PatientMedicijnGebruikPad_c0_r0() {
    return ((Boolean) (BaseDispatcher__cdm_lang.INSTANCE.dispatch(Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_C0_COLUMN.get(this), "gelijk", (Object) Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("VKA")}))));
  }
  public AntistollingsPad_Concept PatientMedicijnGebruikPad_c1_r0() {
    return new AntistollingsPad_Concept("VKA");
  }
  public Boolean PatientMedicijnGebruikPad_c0_r1() {
    return ((Boolean) (BaseDispatcher__cdm_lang.INSTANCE.dispatch(Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_C0_COLUMN.get(this), "gelijk", (Object) Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("DOAC")}))));
  }
  public AntistollingsPad_Concept PatientMedicijnGebruikPad_c1_r1() {
    return new AntistollingsPad_Concept("DOAC");
  }
  public Boolean PatientMedicijnGebruikPad_c0_r2() {
    return ((Boolean) (BaseDispatcher__cdm_lang.INSTANCE.dispatch(Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_C0_COLUMN.get(this), "gelijk", (Object) Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("TAR")}))));
  }
  public AntistollingsPad_Concept PatientMedicijnGebruikPad_c1_r2() {
    return new AntistollingsPad_Concept("TAR");
  }
  public Boolean PatientMedicijnGebruikPad_c0_r3() {
    return ((Boolean) (BaseDispatcher__cdm_lang.INSTANCE.dispatch(Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_C0_COLUMN.get(this), "gelijk", (Object) Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("TAR-P2Y12-remmers")}))));
  }
  public AntistollingsPad_Concept PatientMedicijnGebruikPad_c1_r3() {
    return new AntistollingsPad_Concept("TAR-P2Y12-remmers");
  }
  public Boolean PatientMedicijnGebruikPad_c0_r4() {
    return ((Boolean) (BaseDispatcher__cdm_lang.INSTANCE.dispatch(Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_C0_COLUMN.get(this), "gelijk", (Object) Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("TAR"), new EnkelvoudigeMedicijnGroep_Concept("TAR-P2Y12-remmers")}))));
  }
  public AntistollingsPad_Concept PatientMedicijnGebruikPad_c1_r4() {
    return new AntistollingsPad_Concept("DAPT");
  }
  public Boolean PatientMedicijnGebruikPad_c0_r5() {
    return ((Boolean) (BaseDispatcher__cdm_lang.INSTANCE.dispatch(Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_C0_COLUMN.get(this), "gelijk", (Object) Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("DOAC"), new EnkelvoudigeMedicijnGroep_Concept("TAR"), new EnkelvoudigeMedicijnGroep_Concept("TAR-P2Y12-remmers")}))));
  }
  public AntistollingsPad_Concept PatientMedicijnGebruikPad_c1_r5() {
    return new AntistollingsPad_Concept("TripleTherapie");
  }
  public Boolean PatientMedicijnGebruikPad_c0_r6() {
    return ((Boolean) (BaseDispatcher__cdm_lang.INSTANCE.dispatch(Patient_Concept.PATIENTMEDICIJNGEBRUIKPAD_C0_COLUMN.get(this), "gelijk", (Object) Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("VKA"), new EnkelvoudigeMedicijnGroep_Concept("TAR"), new EnkelvoudigeMedicijnGroep_Concept("TAR-P2Y12-remmers")}))));
  }
  public AntistollingsPad_Concept PatientMedicijnGebruikPad_c1_r6() {
    return new AntistollingsPad_Concept("TripleTherapie");
  }

  public static class ConceptUniverse extends Patient_Concept implements CDSUniverse {
    private static final MutableClass D_CLASS = CDSClass.of(ConceptUniverse.class);

    public ConceptUniverse(Object id) {
      super(id);
    }

    @Override
    public MutableClass dClass() {
      return ConceptUniverse.D_CLASS;
    }
  }
  private static <T> T as_xl4sqf_a0a0a53(Object o, Class<T> type) {
    return (type.isInstance(o) ? (T) o : null);
  }
  private static <T> T as_xl4sqf_a0a0a0a0a53(Object o, Class<T> type) {
    return (type.isInstance(o) ? (T) o : null);
  }
}
