package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.cds.runtime.CDSInstanceTable;
import org.modelingvalue.collections.Collection;
import org.modelingvalue.cds.runtime.CDSObject;
import org.modelingvalue.collections.Set;

public class Patienten_ObjectTable implements CDSInstanceTable {
  @Override
  public Collection<? extends CDSObject> getInstances() {
    return Collection.of(of("Piet", Set.of(new Object[]{new MedicijnGebruik_Concept("MedPiet1"), new MedicijnGebruik_Concept("MedPiet2")}), new AntistollingsPad_Concept("DAPT")), of("Jan", Set.of(new Object[]{new MedicijnGebruik_Concept("MedJan1"), new MedicijnGebruik_Concept("MedJan2")}), new AntistollingsPad_Concept("TripleTherapie")), of("Klaas", Set.of(new Object[]{new MedicijnGebruik_Concept("MedKlaas1"), new MedicijnGebruik_Concept("MedKlaas2"), new MedicijnGebruik_Concept("MedKlass3")}), new AntistollingsPad_Concept("TripleTherapie")));
  }
  private CDSObject of(String id, Set medicijnenGebruik, AntistollingsPad_Concept antistollingsPad) {
    Patient_Concept o = new Patient_Concept(id);
    Patient_Concept.MEDICIJNENGEBRUIK_OBSERVED.set(o, medicijnenGebruik);
    Patient_Concept.ANTISTOLLINGSPAD_OBSERVED.set(o, antistollingsPad);
    return o;
  }
}
