package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.cds.runtime.CDSStoreAndFactory;
import cdm.lang.java.BaseDispatcher__cdm_lang;
import org.modelingvalue.collections.Collection;

public class PatientAntistollingsPad_StoreAndFactory extends CDSStoreAndFactory {
  public PatientAntistollingsPad_StoreAndFactory(String id) {
    super(id);
  }

  @Override
  public Class<?> getUniverseClass() {
    return Patient_Concept.class;
  }

  @Override
  public Class<?> getBaseDispatcherClass() {
    return BaseDispatcher__cdm_lang.class;
  }

  @Override
  protected Collection<Class<?>> getConceptClasses() {
    return ((Collection<Class<?>>) ((Collection) Collection.of(Patient_Concept.class, MedicijnGebruik_Concept.class, Medicijn_Concept.class, MedicijnGroep_Concept.class, AntistollingsPad_Concept.class)));
  }

  @Override
  protected Collection<Class<?>> getInstanceTableClasses() {
    return ((Collection<Class<?>>) ((Collection) Collection.of(AntistollingsPaden_ObjectTable.class, Medicijnen_ObjectTable.class, MedicijnGroepen_ObjectTable.class, Patienten_ObjectTable.class, MedicijnGebruiken_ObjectTable.class)));
  }
}
