package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.cds.runtime.CDSInstanceTable;
import org.modelingvalue.collections.Collection;
import org.modelingvalue.cds.runtime.CDSObject;

public class SpecifiekeMedicijnen_ObjectTable implements CDSInstanceTable {
  @Override
  public Collection<? extends CDSObject> getInstances() {
    return Collection.of(of("sintrom mitis", new GeneriekMedicijn_Concept("acenocoumarol")), of("marcoumar", new GeneriekMedicijn_Concept("fenprocoumon")), of("pradaxa", new GeneriekMedicijn_Concept("dabigatran")), of("xarelto", new GeneriekMedicijn_Concept("rivaroxaban")), of("eliquis", new GeneriekMedicijn_Concept("apixaban")), of("lixiana", new GeneriekMedicijn_Concept("edoxaban")), of("aspirine", new GeneriekMedicijn_Concept("acetylsalicylzuur")), of("ascal", new GeneriekMedicijn_Concept("carbasalaatcalcium")), of("persantin", new GeneriekMedicijn_Concept("dipyridamol")), of("grepid", new GeneriekMedicijn_Concept("clopidogrel")), of("plavix", new GeneriekMedicijn_Concept("clopidogrel")), of("iscover", new GeneriekMedicijn_Concept("clopidogrel")), of("efient", new GeneriekMedicijn_Concept("prasugrel")), of("brilique", new GeneriekMedicijn_Concept("ticagrelor")));
  }
  private CDSObject of(String id, GeneriekMedicijn_Concept generiek) {
    SpecifiekMedicijn_Concept o = new SpecifiekMedicijn_Concept(id);
    SpecifiekMedicijn_Concept.GENERIEK_OBSERVED.set(o, generiek);
    return o;
  }
}
