package serviceLogic;

/*Generated by MPS */

import org.modelingvalue.cds.runtime.CDSInstanceTable;
import org.modelingvalue.collections.Collection;
import org.modelingvalue.cds.runtime.CDSObject;
import org.modelingvalue.collections.Set;

public class SpecifiekeMedicijnen_ObjectTable implements CDSInstanceTable {
  @Override
  public Collection<? extends CDSObject> getInstances() {
    return Collection.of(of("sintrom mitis", new GeneriekMedicijn_Concept("acenocoumarol"), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("VKA")})), of("marcoumar", new GeneriekMedicijn_Concept("fenprocoumon"), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("VKA")})), of("pradaxa", new GeneriekMedicijn_Concept("dabigatran"), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("DOAC")})), of("xarelto", new GeneriekMedicijn_Concept("rivaroxaban"), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("DOAC")})), of("eliquis", new GeneriekMedicijn_Concept("apixaban"), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("DOAC")})), of("lixiana", new GeneriekMedicijn_Concept("edoxaban"), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("DOAC")})), of("aspirine", new GeneriekMedicijn_Concept("acetylsalicylzuur"), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("TAR")})), of("ascal", new GeneriekMedicijn_Concept("carbasalaatcalcium"), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("TAR")})), of("persantin", new GeneriekMedicijn_Concept("dipyridamol"), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("TAR")})), of("grepid", new GeneriekMedicijn_Concept("clopidogrel"), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("TAR-P2Y12-remmers")})), of("plavix", new GeneriekMedicijn_Concept("clopidogrel"), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("TAR-P2Y12-remmers")})), of("iscover", new GeneriekMedicijn_Concept("clopidogrel"), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("TAR-P2Y12-remmers")})), of("efient", new GeneriekMedicijn_Concept("prasugrel"), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("TAR-P2Y12-remmers")})), of("brilique", new GeneriekMedicijn_Concept("ticagrelor"), Set.of(new Object[]{new EnkelvoudigeMedicijnGroep_Concept("TAR-P2Y12-remmers")})));
  }
  private CDSObject of(String id, GeneriekMedicijn_Concept generiek, Set samenstelling) {
    SpecifiekMedicijn_Concept o = new SpecifiekMedicijn_Concept(id);
    SpecifiekMedicijn_Concept.GENERIEK_OBSERVED.set(o, generiek);
    SpecifiekMedicijn_Concept.SAMENSTELLING_OBSERVED.set(o, samenstelling);
    return o;
  }
}
